### ISSUE TITLE
Ускорить генерацию - она не должна тормозить каждый билд

### ISSUE THREAD

**Issue by avitenberg** [yumapos/Yumapos-WCF-Generator#24]
Детектить какие проекты реально изменились, чтобы при изменении, к примеру, тестового проекта Рослин не пытался перегенерить все что можно

Варианты имплементации:
1. Спросить гит в командной строке какие файлы изменились, если они из тех фолдеров которые интересуют генератор - перегенерить
2. Хранить список тех файлов которые интересуют генератор. Если у них поменялась дата последнего изменения, или в этом списке появился новый файл, или какой-то файл исчез - перегенерить

Возможно, понадобится ключ для форсированной перегенерации всего, и он должен быть включен на сервере

**Comment by AntonSmirnovYumasoft** [comment]
Ну мой первый вариант такой прямо в **generation.bat** прописать получение списка измененных файлов искать вхождение имени папки проекта с DO
Вносить в логику генератора эту проверку наверно не стоит, ведь сорцы могут лежать не в репозитории.

Практически рабочий скрипт, но проверка через переменную %errorlevel% не всегда работает, не знаю почему но не выдает ошибки когда строки нет 
```bat
echo off

echo YumaPos.Server.Infrastructure > list.txt
echo YumaPos.FrontEnd.Infrastructure >> list.txt
echo YumaPos.FrontEnd.Data.Infractructure >> list.txt

"%ProgramFiles%\Git\bin\git.exe" ls-files -m --full-name > status.txt

for /F %%i in (list.txt) do (
findstr %%i < status.txt
if %errorlevel%==0 (GOTO generation)
)

GOTO exit

:generation
..\..\Submodule.YumaPos.WcfGenerator\WCF-Generator.exe ..\..\WCF-Generator.exe.config

:exit
```

**Comment by AntonSmirnovYumasoft** [comment]
Второй вариант не рассматриваю, как вообще представляется составление этого списка?

**Comment by AntonSmirnovYumasoft** [comment]
Как вариант можно выдать окно yes|no 
```cmd
@echo off
echo wscript.quit MsgBox ("Run generator?", 4, "WCF Generator") > yesno.vbs
wscript //nologo yesno.vbs
set value=%errorlevel%
del yesno.vbs
if "%value%"=="7" goto exit
:generation
..\..\Submodule.YumaPos.WcfGenerator\WCF-Generator.exe  ..\..\WCF-Generator.exe.config
:exit
```
Ну или в прямо в генераторе выдавать окно + таймер секунды 3 для выбора по дефолту не генерить

**Comment by AntonSmirnovYumasoft** [comment]
Пока нет решения. Вариант с вынесением в отдельное решение не дает ощутимой прибавки по скорости. Нужно тут хорошо подумать. А пока просто на время локального тестирования выключать генерацию.
